### ISSUE TITLE
Document if Qminer is distributed

### ISSUE THREAD

**Issue by nponeccop** [qminer/qminer#560]
Readme.md currently suggests that qminer can be distributed over network nodes:

> It is designed for scaling to millions of instances

However, there is nothing about running the instances or scaling elsewhere

**Comment by blazf** [comment]
Hi, _instances_ in the readme.md relates to data points (e.g. documents, transactons) and not network nodes. I've updated the readme file to remove future confusions. Otherwise we optimized qminer to run on single machines. Distribution (i.e. running multiple instances of qminer) is handled by separate project called [qtopology](https://github.com/qminer/qtopology).
