### ISSUE TITLE
test-aggr.cpp

### ISSUE THREAD

**Issue by eParadigme** [qminer/qminer#601]
On test-aggr.cpp
TEST(TSlottedHistogramTest, Simple1) {
	try {
		TQm::TStreamAggrs::PSlottedHistogram obj = TQm::TStreamAggrs::TSlottedHistogram::New(20, 2, 3);

PSlottedHistogram  and TSlottedHistogram are not members of TStreamAggrs

**Comment by bergloman** [comment]
While fixing this issue I am also testing another C++ unit test framework - google test is not cloud-deploy friendly.

I tested https://github.com/catchorg/Catch2 - it seems overly complex and there are some strange collisions of macros with glib. It also weighs 0.5 MB.

I am now exploring https://github.com/torpedro/microtest.h - just 7kB of readable code - it work perfectly so far, and has been successfully integrated into gyp and built in Travis. Running the tests is not yet enabled, however the code will be built together with the main code, so that test cases don't get stale - which is what happened now.

**Comment by bergloman** [comment]
I ported C++ tests to a simpler library - `https://github.com/torpedro/microtest.h `.
Tests are now ready to run on Travis, I just need to get a PR accepted.
